export PLAYWRIGHT_BROWSERS_PATH=$HOME/ms-playwright
source ${HOME}/.config/zsh/source.sh

ZSH_THEME="robbyrussell"
export ZSH="$HOME/.oh-my-zsh"

plugins=(
  git
  z
  brew
  npm
  docker
  docker-compose
  gh
)

source $ZSH/oh-my-zsh.sh
export NVM_DIR="$HOME/.nvm"

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

export PATH="/home/linuxbrew/.linuxbrew/opt/php@8.2/bin:$PATH"
export PATH="/home/linuxbrew/.linuxbrew/opt/php@8.2/sbin:$PATH"
export VISUAL=nvim 
export EDITOR="$VISUAL"
export PATH="/home/linuxbrew/.linuxbrew/opt/php@8.2/bin:$PATH"
export PATH="/home/linuxbrew/.linuxbrew/opt/php@8.2/sbin:$PATH"


# Load Angular CLI autocompletion.
source <(ng completion script)
