# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export PLAYWRIGHT_BROWSERS_PATH=$HOME/ms-playwright
source ${HOME}/.config/zsh/source.sh

# ZSH_THEME="frontcube"
ZSH_THEME="powerlevel10k/powerlevel10k"
export ZSH="$HOME/.oh-my-zsh"

plugins=(
  git
  z
  brew
  npm
  docker
  docker-compose
  gh
)

source $ZSH/oh-my-zsh.sh
export NVM_DIR="$HOME/.nvm"

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

export PATH="/home/linuxbrew/.linuxbrew/opt/php@8.2/bin:$PATH"
export PATH="/home/linuxbrew/.linuxbrew/opt/php@8.2/sbin:$PATH"
export VISUAL=nvim 
export EDITOR="$VISUAL"
export PATH="/home/linuxbrew/.linuxbrew/opt/php@8.2/bin:$PATH"
export PATH="/home/linuxbrew/.linuxbrew/opt/php@8.2/sbin:$PATH"


# Load Angular CLI autocompletion.
source <(ng completion script)

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

alias ls="eza --tree --level=1 --icons=always --no-time --no-user --no-permissions"
